export {default as httpCodes} from './httpCodes';
export {default as languages} from './languages';
export {default as colors} from './colors';
export {default as urls} from './urls';
export {default as fonts} from './fonts';
export {default as metrics} from './metrics';
export {default as strings} from './strings';
export * from './customMapStyle';
export * from './theme';
export {ios, android} from './platform';
export {top, bottom} from './safeSpaces';